// Code generated by "stringer -type=SegmentType -linecomment"; DO NOT EDIT.

package vmwriter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Const-0]
	_ = x[Arg-1]
	_ = x[Local-2]
	_ = x[Static-3]
	_ = x[This-4]
	_ = x[That-5]
	_ = x[Pointer-6]
	_ = x[Temp-7]
}

const _SegmentType_name = "constantargumentlocalstaticthisthatpointertemp"

var _SegmentType_index = [...]uint8{0, 8, 16, 21, 27, 31, 35, 42, 46}

func (i SegmentType) String() string {
	if i < 0 || i >= SegmentType(len(_SegmentType_index)-1) {
		return "SegmentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SegmentType_name[_SegmentType_index[i]:_SegmentType_index[i+1]]
}
